// This file was generated by lezer-generator. You probably shouldn't edit it.
const {LRParser} = require("@lezer/lr")
exports.parser = LRParser.deserialize({
  version: 14,
  states: "#YQYQPOOOOQO'#C_'#C_ObQPO'#CiOOQO'#Cc'#CcQYQPOOOgQPO,59TOOQO-E6a-E6aOOQO'#Cd'#CdOuQPO'#CbO!TQPO'#CkO!]QPO1G.oOOQO-E6b-E6bOgQPO'#CeO!bQPO,59VOOQO7+$Z7+$ZOOQO,59P,59POOQO-E6c-E6c",
  stateData: "!j~O[OSPOS~OSPOTPO~O^TO~OSVOTVO`UPaUP~OSVOTVO`UXaUX~O`[Oa_X~Oa^O~O`[Oa_a~O",
  goto: "!V`PPPaPPekqxPPP!OP!STQOSQXTR_[QSORUSSWT[RZWQ]XR`]TROSRYT",
  nodeNames: "⚠ LineComment Rules Head Symbol QuotedSymbol Production",
  maxTerm: 17,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "(P~RfX^!gpq!grs#[st%Otu%gwx%{}!O'j!O!P'u![!]'p!]!^'u!c!}%g#R#S%g#T#o%g#p#q'z#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lY[~X^!gpq!g#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~#_WOY#[Zr#[rs#ws#O#[#O#P#|#P;'S#[;'S;=`$x<%lO#[~#|OT~~$PRO;'S#[;'S;=`$Y;=`O#[~$]XOY#[Zr#[rs#ws#O#[#O#P#|#P;'S#[;'S;=`$x;=`<%l#[<%lO#[~${P;=`<%l#[~%TSP~OY%OZ;'S%O;'S;=`%a<%lO%O~%dP;=`<%l%O~%lTS~tu%g!Q![%g!c!}%g#R#S%g#T#o%g~&OWOY%{Zw%{wx#wx#O%{#O#P&h#P;'S%{;'S;=`'d<%lO%{~&kRO;'S%{;'S;=`&t;=`O%{~&wXOY%{Zw%{wx#wx#O%{#O#P&h#P;'S%{;'S;=`'d;=`<%l%{<%lO%{~'gP;=`<%l%{~'mP!`!a'p~'uO^~~'zOa~~(PO`~",
  tokenizers: [0],
  topRules: {"Rules":[0,2]},
  tokenPrec: 0
})
