// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  rules = 1,
  Head = 2,
  Symbol = 3,
  QuotedSymbol = 4,
  Production = 5,
  Group = 6,
  Optional = 7,
  Repeat0 = 8,
  Repeat1 = 9
